#!/usr/bin/bash
while true
do
    pkill -f "python3 /home/altair/Dropbox/code/GNOMEodoro/pomodoro_counter.py"
    /home/altair/Dropbox/code/GNOMEodoro/pomodoro_counter.py &
    sleep $(($(date -d '2am tomorrow' +%s) - $(date +%s)))
done
